feat(deprecation): add ability to deprecate packages
cdklabs/cdk-cloudformation pull request #15
Opened 2021-12-09 19:49 UTC by corymhall

This introduces the ability to deprecate packages. This gets a little
tricky because we are publishing to multiple package managers which each
handle deprecation differently. For example, with NPM you can run an npm
command, but it's not currently possible
to "deprecate" a package on PyPI, and on Nuget it must be done manually.

Because of this, and because npm seems to currently be the source of
truth for CDK Constructs (e.g. Construct Hub) I am only "deprecating"
packages on npm.

When a user adds a package to the list of `deprecateTypes`, it will

1. Add a disclaimer to the package README that the package is deprecated
2. Remove the build/release workflows for the package
3. Add an npm deprecate workflow for the package

It is also possible to un-deprecate a package on npm by running `npm
deprecate` with an empty message. This update also handles that scenario
if an empty string is provided in `deprecateTypes`

fixes #13

2021-12-09 19:49 UTC, corymhall commented on projenrc/type-package.ts
> +          { run: 'echo "//${{ env.NPM_REGISTRY }}/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc' },
I'm not sure this is the correct way to do this...

2021-12-12 14:45 UTC, eladb requested changes
If we remove the release workflows for the deprecated packages, then non-npm package managers won't see the deprecation. I am wondering if the right thing to do is toL

* Mark it as `deprecated` in `package.json`
* Announce that it is deprecated in `README.md`
* Stop taking registry updates for it
* Continue to publish to all package managers.

We can then decide if we want to actually deprecate it "officially" or just leave it like that.

Maybe we can also special-case this in the Construct Hub so that these will be filtered out even if they are not officially marked as deprecated.

Thoughts?

2021-12-13 14:05 UTC, corymhall commented
Yeah I think that makes the most sense. We can always add the package to `excludeTypes` if we want to stop publishing at any point.

Does the `deprecated` property in `package.json` have any function, or is it just for documentation? If this is part of the info that Construct Hub picks up then maybe they can use this to filter.

2021-12-13 14:27 UTC, eladb commented
I don't believe it has any function (see https://docs.npmjs.com/cli/v8/configuring-npm/package-json)

2022-01-12 06:01 UTC, eladb commented
@corymhall ping

2022-01-13 14:51 UTC, corymhall commented
I should be able to get to this in the next couple of days.

2022-01-25 10:24 UTC, eladb approved these changes
GREAT JOB!

2022-01-25 12:47 UTC, merged